### ISSUE TITLE
`anki-editor-insert-note` inserting new note as subheading of previous level-1 heading note

### ISSUE THREAD

**Issue by Aneeqasif** [anki-editor/anki-editor#62]
it donot happen if the cursor is on a level-1 heading or outside the scope of any other level other then level-1
for example if cursor is under level-2 heading the new note heading will be be level-2 

[Screencast_20240919_231437.webm](https://github.com/user-attachments/assets/b11ccdd8-3f6f-4986-82bd-b84f8602293d)

**Comment by slotThe** [comment]
This is documented:

> The note is placed after the current subtree, at the same level as the heading closest before point.

Whether this is good behaviour or not is to be debated (I would also tend to "no"), but breaking this just because some people don't like it also does not seem like the best idea :)

**Comment by Aneeqasif** [comment]
that is just fine if it is default behaviour then i must be using the package in wrong way. can you please guide me what is the way of creating new notes as the way i am doing it using the command it just keep nesting the newly created note under previous one that just feels wrong.

2. if adjusting the note levels after creating it OR running `anki-editor-insert-note` while puting cursor on a level-1 heading are the only ways to work can you please give me some custom snippet that i can use so that it donot break the default functionality as well as allow me to use it in different way. if it is too much then it fine no problem. just guide me how you use it

3. one more thing i want to ask you how can i syntax highligh the code snippets that are exported. I have tried alot but cannt find the way other then using `inline-css` in `org-html-htmlize-output-type` that i donot wanna use. 

I appreciate any help.

**Comment by slotThe** [comment]
> that is just fine if it is default behaviour then i must be using the package in wrong way. can you please guide me what is the way of creating new notes as the way i am doing it using the command it just keep nesting the newly created note under previous one that just feels wrong.
>
>     2. if adjusting the note levels after creating it OR running `anki-editor-insert-note` while puting cursor on a level-1 heading are the only ways to work can you please give me some custom snippet that i can use so that it donot break the default functionality as well as allow me to use it in different way. if it is too much then it fine no problem. just guide me how you use it

I use something like this:

``` emacs-lisp
(cl-defun slot/org-new-anki-node (name &key type use-deck level)
    "Create a new anki node in any Org file.
If NAME is not specified, use a random 32-bit unsigned int for the
string.  If TYPE is \"Cloze\", insert a cloze deletion; if it is nil,
insert a \"Basic\" card template.  If USE-DECK is a string, use that
string as the deck name; otherwise, query the user.  LEVEL is the level
the headline should be set at; if this is nil, make a guess based on
'org-current-level'."
  (interactive
   (list (read-string "Name (optional): " nil nil (int-to-string (cl-random (1- (expt 2 32)))))))
  (let ((lvl (or level
                 (max 1 (or (progn (anki-editor--goto-nearest-note-type)
                                   (org-current-level))
                            0))))
        (type (or type "Basic"))
        (use-deck (when use-deck
                    (if (stringp use-deck)
                        use-deck
                      (completing-read "Deck: " (anki-editor-api-call-result 'deckNames))))))
    (insert (concat (make-string lvl ?*) " " name))
    (insert (format "\n:PROPERTIES:%s\n:ANKI_NOTE_TYPE: %s\n:END:\n"
                    (if use-deck (format "\n:ANKI_DECK: %s" use-deck) "")
                    type))
    (if (string= type "Cloze")
        (insert (concat (make-string (1+ lvl) ?*) " Text"))
      (insert (concat (make-string (1+ lvl) ?*) " Front\n"))
      (insert (concat (make-string (1+ lvl) ?*) " Back\n"))
      (search-backward "Front"))
    (end-of-line)
    (newline)))

(defun slot/anki-node (&optional arg)
  (interactive "P")
  (slot/org-new-anki-node
   (read-string "Name (optional): " nil nil (int-to-string (cl-random (1- (expt 2 32)))))
   :type (if arg "Cloze" "Basic")
   :level (let ((lvl (max 1 (1- (or (org-current-level) 0)))))
            (if (= 1 lvl) (1+ lvl) lvl))))
```

and then bind `slot/anki-node` to a key. Perhaps this is more to your liking?

>     3. one more thing i want to ask you how can i syntax highligh the code snippets that are exported. I have tried alot but cannt find the way other then using `inline-css` in `org-html-htmlize-output-type` that i donot wanna use.

This is automatically done; you just have to execute `anki-editor-copy-styles` to pull in the relevant CSS into Anki.

**Comment by Aneeqasif** [comment]
first of all thanks alot for the response. yeah i tried `anki-editor-copy-styles` it do pull some styles and make the code in a grey box with monospace font but the code sytax high light is not working i might be doing something wrong.

![image](https://github.com/user-attachments/assets/a9d999a7-5b59-44fc-bdd6-4cbedf131195)


after running the command I get this in the card styling
```css
</style>
<!-- {{ Emacs Org-mode -->
<!-- Updated: Fri Sep 20 22:24:15 2024 -->
<style type="text/css">
  #content { max-width: 60em; margin: auto; }
  .title  { text-align: center;
             margin-bottom: .2em; }
  .subtitle { text-align: center;
              font-size: medium;
              font-weight: bold;
              margin-top:0; }
  .todo   { font-family: monospace; color: red; }
  .done   { font-family: monospace; color: green; }
  .priority { font-family: monospace; color: orange; }
  .tag    { background-color: #eee; font-family: monospace;
            padding: 2px; font-size: 80%; font-weight: normal; }
  .timestamp { color: #bebebe; }
  .timestamp-kwd { color: #5f9ea0; }
  .org-right  { margin-left: auto; margin-right: 0px;  text-align: right; }
  .org-left   { margin-left: 0px;  margin-right: auto; text-align: left; }
  .org-center { margin-left: auto; margin-right: auto; text-align: center; }
  .underline { text-decoration: underline; }
  #postamble p, #preamble p { font-size: 90%; margin: .2em; }
  p.verse { margin-left: 3%; }
  pre {
    border: 1px solid #e6e6e6;
    border-radius: 3px;
    background-color: #f2f2f2;
    padding: 8pt;
    font-family: monospace;
    overflow: auto;
    margin: 1.2em;
  }
  pre.src {
    position: relative;
    overflow: auto;
  }
  pre.src:before {
    display: none;
    position: absolute;
    top: -8px;
    right: 12px;
    padding: 3px;
    color: #555;
    background-color: #f2f2f299;
  }
  pre.src:hover:before { display: inline; margin-top: 14px;}
  /* Languages per Org manual */
  pre.src-asymptote:before { content: 'Asymptote'; }
  pre.src-awk:before { content: 'Awk'; }
  pre.src-authinfo::before { content: 'Authinfo'; }
  pre.src-C:before { content: 'C'; }
  /* pre.src-C++ doesn't work in CSS */
  pre.src-clojure:before { content: 'Clojure'; }
  pre.src-css:before { content: 'CSS'; }
  pre.src-D:before { content: 'D'; }
  pre.src-ditaa:before { content: 'ditaa'; }
  pre.src-dot:before { content: 'Graphviz'; }
  pre.src-calc:before { content: 'Emacs Calc'; }
  pre.src-emacs-lisp:before { content: 'Emacs Lisp'; }
  pre.src-fortran:before { content: 'Fortran'; }
  pre.src-gnuplot:before { content: 'gnuplot'; }
  pre.src-haskell:before { content: 'Haskell'; }
  pre.src-hledger:before { content: 'hledger'; }
  pre.src-java:before { content: 'Java'; }
  pre.src-js:before { content: 'Javascript'; }
  pre.src-latex:before { content: 'LaTeX'; }
  pre.src-ledger:before { content: 'Ledger'; }
  pre.src-lisp:before { content: 'Lisp'; }
  pre.src-lilypond:before { content: 'Lilypond'; }
  pre.src-lua:before { content: 'Lua'; }
  pre.src-matlab:before { content: 'MATLAB'; }
  pre.src-mscgen:before { content: 'Mscgen'; }
  pre.src-ocaml:before { content: 'Objective Caml'; }
  pre.src-octave:before { content: 'Octave'; }
  pre.src-org:before { content: 'Org mode'; }
  pre.src-oz:before { content: 'OZ'; }
  pre.src-plantuml:before { content: 'Plantuml'; }
  pre.src-processing:before { content: 'Processing.js'; }
  pre.src-python:before { content: 'Python'; }
  pre.src-R:before { content: 'R'; }
  pre.src-ruby:before { content: 'Ruby'; }
  pre.src-sass:before { content: 'Sass'; }
  pre.src-scheme:before { content: 'Scheme'; }
  pre.src-screen:before { content: 'Gnu Screen'; }
  pre.src-sed:before { content: 'Sed'; }
  pre.src-sh:before { content: 'shell'; }
  pre.src-sql:before { content: 'SQL'; }
  pre.src-sqlite:before { content: 'SQLite'; }
  /* additional languages in org.el's org-babel-load-languages alist */
  pre.src-forth:before { content: 'Forth'; }
  pre.src-io:before { content: 'IO'; }
  pre.src-J:before { content: 'J'; }
  pre.src-makefile:before { content: 'Makefile'; }
  pre.src-maxima:before { content: 'Maxima'; }
  pre.src-perl:before { content: 'Perl'; }
  pre.src-picolisp:before { content: 'Pico Lisp'; }
  pre.src-scala:before { content: 'Scala'; }
  pre.src-shell:before { content: 'Shell Script'; }
  pre.src-ebnf2ps:before { content: 'ebfn2ps'; }
  /* additional language identifiers per "defun org-babel-execute"
       in ob-*.el */
  pre.src-cpp:before  { content: 'C++'; }
  pre.src-abc:before  { content: 'ABC'; }
  pre.src-coq:before  { content: 'Coq'; }
  pre.src-groovy:before  { content: 'Groovy'; }
  /* additional language identifiers from org-babel-shell-names in
     ob-shell.el: ob-shell is the only babel language using a lambda to put
     the execution function name together. */
  pre.src-bash:before  { content: 'bash'; }
  pre.src-csh:before  { content: 'csh'; }
  pre.src-ash:before  { content: 'ash'; }
  pre.src-dash:before  { content: 'dash'; }
  pre.src-ksh:before  { content: 'ksh'; }
  pre.src-mksh:before  { content: 'mksh'; }
  pre.src-posh:before  { content: 'posh'; }
  /* Additional Emacs modes also supported by the LaTeX listings package */
  pre.src-ada:before { content: 'Ada'; }
  pre.src-asm:before { content: 'Assembler'; }
  pre.src-caml:before { content: 'Caml'; }
  pre.src-delphi:before { content: 'Delphi'; }
  pre.src-html:before { content: 'HTML'; }
  pre.src-idl:before { content: 'IDL'; }
  pre.src-mercury:before { content: 'Mercury'; }
  pre.src-metapost:before { content: 'MetaPost'; }
  pre.src-modula-2:before { content: 'Modula-2'; }
  pre.src-pascal:before { content: 'Pascal'; }
  pre.src-ps:before { content: 'PostScript'; }
  pre.src-prolog:before { content: 'Prolog'; }
  pre.src-simula:before { content: 'Simula'; }
  pre.src-tcl:before { content: 'tcl'; }
  pre.src-tex:before { content: 'TeX'; }
  pre.src-plain-tex:before { content: 'Plain TeX'; }
  pre.src-verilog:before { content: 'Verilog'; }
  pre.src-vhdl:before { content: 'VHDL'; }
  pre.src-xml:before { content: 'XML'; }
  pre.src-nxml:before { content: 'XML'; }
  /* add a generic configuration mode; LaTeX export needs an additional
     (add-to-list 'org-latex-listings-langs '(conf " ")) in .emacs */
  pre.src-conf:before { content: 'Configuration File'; }

  table { border-collapse:collapse; }
  caption.t-above { caption-side: top; }
  caption.t-bottom { caption-side: bottom; }
  td, th { vertical-align:top;  }
  th.org-right  { text-align: center;  }
  th.org-left   { text-align: center;   }
  th.org-center { text-align: center; }
  td.org-right  { text-align: right;  }
  td.org-left   { text-align: left;   }
  td.org-center { text-align: center; }
  dt { font-weight: bold; }
  .footpara { display: inline; }
  .footdef  { margin-bottom: 1em; }
  .figure { padding: 1em; }
  .figure p { text-align: center; }
  .equation-container {
    display: table;
    text-align: center;
    width: 100%;
  }
  .equation {
    vertical-align: middle;
  }
  .equation-label {
    display: table-cell;
    text-align: right;
    vertical-align: middle;
  }
  .inlinetask {
    padding: 10px;
    border: 2px solid gray;
    margin: 10px;
    background: #ffffcc;
  }
  #org-div-home-and-up
   { text-align: right; font-size: 70%; white-space: nowrap; }
  textarea { overflow-x: auto; }
  .linenr { font-size: smaller }
  .code-highlighted { background-color: #ffff00; }
  .org-info-js_info-navigation { border-style: none; }
  #org-info-js_console-label
    { font-size: 10px; font-weight: bold; white-space: nowrap; }
  .org-info-js_search-highlight
    { background-color: #ffff00; color: #000000; font-weight: bold; }
  .org-svg { }
</style>
<!-- Emacs Org-mode }} -->
<style>

.card {
    font-family: arial;
    font-size: 20px;
    text-align: center;
    color: black;
    background-color: white;
}

```
